### ISSUE TITLE
Latest Code?

### ISSUE THREAD

**Issue by kbsymanz** [guardianproject/notecipher#14]
It seems to me that the app that is hosted on the Play Store is more recent that the sources in Github. I say that because the `android:versionCode` in the manifest in the Play Store is 11 while on Github it is 10. Also, some behavior is different between the Play Store version and what I compile and run myself based upon the Github sources.

If this is the case, can the source code on Github be updated to the latest to match the Play Store? I would like to submit more pull requests but I want to be working with the latest code.

**Comment by eighthave** [comment]
It does look like there is a mismatch between the git repo and the latest release in the Play Store. Thanks for the bug report!  @n8fr8 can you take a look at your local repo?

**Comment by n8fr8** [comment]
Looking into it...

**Comment by n8fr8** [comment]
I did find some unpush commits on my old dev box, and that was where I produced the last Play update. Those have now been pushed to master.

Now the git repo is more up to date now due to using the new CacheWord library, so we will have to work through pushing a new release out.
