### ISSUE TITLE
Set p/w dialog should lay out 2 fields in same popup

### ISSUE THREAD

**Issue by djhalliday** [guardianproject/notecipher#4]
Easier / more straightforward than having two subsequent popups.

**Comment by n8fr8** [comment]
i am confused? there should just be one popup

**Comment by n8fr8** [comment]
oh i think it just popped up twice b/c it will always show the dialog when onResume() is called. 

the UI is veeeery simple obviously. However, i think we can build in the dialog box options into our library, as well as a paassword cache timeout feature. The more we can standardize for other devs, the better.

**Comment by djhalliday** [comment]
ah, yes - that makes sense. re:UI, agreed. right balance between basic and standardized should be simple enough to find.

**Comment by abeluck** [comment]
Closing stale bug report. Integration of Cacheword overhauled the password screen.
