### ISSUE TITLE
Problem with ant build??

### ISSUE THREAD

**Issue by jcarlson23** [guardianproject/notecipher#5]
So I just pulled from the repo, updated the project via the command line so I could build using ant:

android update project --name notepadbot --target 3 --path .

Compilation works just fine, but upon deployment I get the following error:

 Added shared lib /data/data/info.guardianproject.notepadbot/lib/libstlport_shared.so 0x40635bf8
D/dalvikvm(  511): No JNI_OnLoad found in /data/data/info.guardianproject.notepadbot/lib/libstlport_shared.so 0x40635bf8, skipping init
D/dalvikvm(  511): Trying to load lib /data/data/info.guardianproject.notepadbot/lib/libsqlcipher.so 0x40635bf8
D/dalvikvm(  511): Added shared lib /data/data/info.guardianproject.notepadbot/lib/libsqlcipher.so 0x40635bf8
D/dalvikvm(  511): No JNI_OnLoad found in /data/data/info.guardianproject.notepadbot/lib/libsqlcipher.so 0x40635bf8, skipping init
D/dalvikvm(  511): Trying to load lib /data/data/info.guardianproject.notepadbot/files/libsqlcipher_android.so 0x40635bf8
D/AndroidRuntime(  511): Shutting down VM
W/dalvikvm(  511): threadid=1: thread exiting with uncaught exception (group=0x40014760)
E/AndroidRuntime(  511): FATAL EXCEPTION: main
E/AndroidRuntime(  511): java.lang.UnsatisfiedLinkError: Cannot load library: load_library[1108]: Library '/data/data/info.guardianproject.notepadbot/files/libsqlcipher_android.so' not found
E/AndroidRuntime(  511):    at java.lang.Runtime.load(Runtime.java:390)
E/AndroidRuntime(  511):    at java.lang.System.load(System.java:534)
E/AndroidRuntime(  511):    at info.guardianproject.database.sqlcipher.SQLiteDatabase.loadLibs(SQLiteDatabase.java:93)
E/AndroidRuntime(  511):    at info.guardianproject.notepadbot.Notepadbot.onCreate(Notepadbot.java:90)
E/AndroidRuntime(  511):    

Is there anything needed explicitly?  I can modify the source and use System.load("/data/data/..../libsqlcipher_android.so") and verify it's loaded, etc, but I still get an error leading me to believe that something is missing...

**Comment by jcarlson23** [comment]
Got same result rebuilding the project in Eclipse...

Ok - so my workaround so far is:

 adb push libsqlcipher_android.so /data/data/info.guardianproject.notepadbot/files/libsqlcipher_android.so

where libsqlcipher_android.so is copied from ""-11.so (the target).  (Advice from Nathan) 

And once that's pushed, then the app runs just fine... but something must missing here to generate an all-inclusive apk...

**Comment by developernotes** [comment]
I am seeing the same issue when deploying from both Eclipse and IntelliJ to a 2.2 simulator.  I have pushed the libsqlcipher_adroid-11.so as libsqlcipher_android.so to the simulator using adb and I continue to get the UnsatisfiedLinkError: Library /data/data/info.guardianproject.notepadbot/files/libsqlcipher_android.so not found.  I am building against the HEAD which is currently 6d07b2f205ac65ac2657e73d7298353712907edc.

Any thoughts?

**Comment by abeluck** [comment]
Not able to reproduce this. Things might've changed in the past two years or so. Pleas re-open if it persists.
