### ISSUE TITLE
app broke with new jars

### ISSUE THREAD

**Issue by holliwood2** [guardianproject/notecipher#6]
The app works as normal but cannot retrieve any notes. After a very quick look I can see that the sqlite3 is throwing a DatabaseObjectNotClosedException when inflating NoteEdit. Looking deeper I can find no database in the /data/data/... folder. However the notes are in the listview. No time to dig deeper now...

**Comment by abeluck** [comment]
This is an old bug report, and NoteCipher has gone through some significant changes. Please reopen this bug if it persists.
