### ISSUE TITLE
no option to open text file via NoteCipher?

### ISSUE THREAD

**Issue by djhalliday** [guardianproject/notecipher#7]
importing a basic .txt file would be a great option to have for notecipher, and probably more useful than the current (working) image import option.

actually i thought that this feature was already built-in, but when selecting a .txt file from a file manager application like ASTRO or the built-in CM File Manager, notecipher doesn't appear to be able to receive that intent.

**Comment by n8fr8** [comment]
That is very strange. Perhaps we need to explicitly choose to support the specific text/plain mimetype? or maybe it isn't being identified correctly as text/plain?

This also may be fixed in the code, but not in the Market version.

**Comment by abeluck** [comment]
Closing stale bug reports.
