### ISSUE TITLE
F/Con start, D/L'd from F-Droid Repo on CM9

### ISSUE THREAD

**Issue by ghost** [guardianproject/notecipher#9]
Simply put, closes immediately when opened with a message saying 'unfortunately, notecipher has stopped'. No visible interface at this point and no setup.

Using CM9 on a Samsung Galaxy S 2, fresh update of the official guardianproject f-droid repo (only 1 notecipher version appears).

Would love to get working, used to.depend on this when I was running stock rom!

**Comment by abeluck** [comment]
Could you install [aLogRec](https://play.google.com/store/apps/details?id=org.jtb.alogrec&hl=en) and capture+post the logs during the crash?

If the log contains sensitive/personal information, feel free to send it to me privately abel at guardianproject dot info (or send it to yourself and edit it on a computer).

**Comment by abeluck** [comment]
Could you install [aLogRec](https://play.google.com/store/apps/details?id=org.jtb.alogrec&hl=en) and capture+post the logs during the crash?

If the log contains sensitive/personal information, feel free to send it to me privately abel at guardianproject dot info (or send it to yourself and edit it on a computer).

**Comment by ghost** [comment]
Hi Abel,
I don't have the Play store installed on my phone/tablet, nor do I care
to install it.. is aLogRec available elsewhere?
Will CatLog or another logcat-derived command from the F-Droid core repo
work?
Thanks,
Cathal

On 23/10/12 14:46, Abel Luck wrote:

> Could you install [aLogRec](https://play.google.com/store/apps/details?id=org.jtb.alogrec&hl=en) and capture+post the logs during the crash?
> 
> If the log contains sensitive/personal information, feel free to send it to me privately abel at guardianproject dot info (or send it to yourself and edit it on a computer).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/guardianproject/notepadbot/issues/9#issuecomment-9702214

## 

www.indiebiotech.com
twitter.com/onetruecathal
joindiaspora.com/u/cathalgarvey
PGP Public Key: http://bit.ly/CathalGKey

**Comment by abeluck** [comment]
Ah, I should have realized that. No worries, I don't want you to install the Play store either ;-) 

Yes, any app that will capture logcat and allow you to save/send it will be fine.

**Comment by n8fr8** [comment]
On 10/23/2012 07:17 PM, Abel Luck wrote:

> Could you install aLogRec
> https://play.google.com/store/apps/details?id=org.jtb.alogrec&hl=en
> and capture+post the logs during the crash?

FYI the issue is that NoteCipher uses an older build of SQLCipher that
doesn't work on Android 4.x

We need to update the app to use the latest SQLCipher.

**Comment by ghost** [comment]
Hi, sorry for delay. Here's filtered output from alogcat, using 'guardianproject' as filter:

I/ActivityManager(  175): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=info.guardianproject.notepadbot/.Notepadbot} from pid 394
I/ActivityManager(  175): Start proc info.guardianproject.notepadbot for activity info.guardianproject.notepadbot/.Notepadbot: pid=14472 uid=10081 gids={1015}
D/dalvikvm(14472): Trying to load lib /data/data/info.guardianproject.notepadbot/lib/libstlport_shared.so 0x40d7a188
D/dalvikvm(14472): Added shared lib /data/data/info.guardianproject.notepadbot/lib/libstlport_shared.so 0x40d7a188
D/dalvikvm(14472): No JNI_OnLoad found in /data/data/info.guardianproject.notepadbot/lib/libstlport_shared.so 0x40d7a188, skipping init
D/dalvikvm(14472): Trying to load lib /data/data/info.guardianproject.notepadbot/lib/libsqlcipher.so 0x40d7a188
D/dalvikvm(14472): Added shared lib /data/data/info.guardianproject.notepadbot/lib/libsqlcipher.so 0x40d7a188
D/dalvikvm(14472): No JNI_OnLoad found in /data/data/info.guardianproject.notepadbot/lib/libsqlcipher.so 0x40d7a188, skipping init
D/dalvikvm(14472): Trying to load lib /data/data/info.guardianproject.notepadbot/files/libsqlcipher_android.so 0x40d7a188
E/AndroidRuntime(14472): java.lang.UnsatisfiedLinkError: Cannot load library: load_library[1120]: Library '/data/data/info.guardianproject.notepadbot/files/libsqlcipher_android.so' not found
E/AndroidRuntime(14472):    at info.guardianproject.database.sqlcipher.SQLiteDatabase.loadLibs(SQLiteDatabase.java:123)
E/AndroidRuntime(14472):    at info.guardianproject.notepadbot.Notepadbot.onCreate(Notepadbot.java:88)
W/ActivityManager(  175):   Force finishing activity info.guardianproject.notepadbot/.Notepadbot
W/ActivityManager(  175): Activity pause timeout for ActivityRecord{40dfe958 info.guardianproject.notepadbot/.Notepadbot}
I/ActivityManager(  175): Process info.guardianproject.notepadbot (pid 14472) has died.
W/ActivityManager(  175): Activity destroy timeout for ActivityRecord{40dfe958 info.guardianproject.notepadbot/.Notepadbot}

n8fr8 notifications@github.com wrote:

> On 10/23/2012 07:17 PM, Abel Luck wrote:
> 
> > Could you install aLogRec
> > https://play.google.com/store/apps/details?id=org.jtb.alogrec&hl=en
> > and capture+post the logs during the crash?
> 
> FYI the issue is that NoteCipher uses an older build of SQLCipher that
> doesn't work on Android 4.x
> 
> We need to update the app to use the latest SQLCipher.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/guardianproject/notepadbot/issues/9#issuecomment-9724367

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by NiveusLuna** [comment]
Is any work being done on NoteCipher to update it to the latest SQLCipher? I don't see any commits here newer than 2011.

Note: I am not asking for an ETA, nor do I want one. I'm a programmer myself. I know full well that any ETA a programmer gives is bull, and being asked for one doesn't help. I just want a boolean here. :P

**Comment by n8fr8** [comment]
noteCipherLives=TRUE;

we are just kicking off another round of work on this app due to demand from a variety of sources.

**Comment by ghost** [comment]
Woohoo!

On 06/12/12 23:27, n8fr8 wrote:

> noteCipherLives=TRUE;
> 
> we are just kicking off another round of work on this app due to demand from a variety of sources.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/guardianproject/notepadbot/issues/9#issuecomment-11111228

## 

www.indiebiotech.com
twitter.com/onetruecathal
PGP Public Key: 3B3DE808 (Verify before serious use)

**Comment by NiveusLuna** [comment]
cout << "Yay!";

**Comment by abeluck** [comment]
Closing stale bug reports.
